name: root
version: 0.0.0
homepage: https://github.com/morloclib/root
synopsis: Define type signatures for common functions
description: A set of function definitions for operating on functions, primitives and basic containers.
category: language-base
license: MIT
author: "Zebulun Arendsee"
maintainer: "z@morloc.io"
github: https://github.com/morloclib/root
bug-reports: https://github.com/morloclib/root
